### ISSUE TITLE
Error when evaluating derivatives for nonstandard domain

### ISSUE THREAD

**Issue by thoeschler** [spectralDNS/shenfun#78]
Hi Mikael,

I am having some troubles when I try to evaluate derivatives for a `Function` with a nonstandard domain. For the standard domain everything works, but not for the nonstandard domain that I am using.

I appended a test code that should explain the problem:
```python
from shenfun import TensorProductSpace, FunctionSpace, comm, Array, project, Dx
from sympy import symbols

# create function spaces
B0 = FunctionSpace(10, 'legendre', bc=None, domain=(0, 100.))
B1 = FunctionSpace(10, 'legendre', bc=None, domain=(0., 50.))
T = TensorProductSpace(comm, (B0, B1))

# create function
x, y = symbols('x, y')
u = x*(x - 100)*y
# project to space
u_function = project(u, T)

# test derivatives
u0 = project(Dx(u_function, 0), T).backward(kind='uniform')
u0_sympy = project(u.diff(x).simplify(), T).backward(kind='uniform')
# this should be zero
print(u0 - u0_sympy)

u1 = project(Dx(u_function, 1), T).backward(kind='uniform')
u1_sympy = project(u.diff(y).simplify(), T).backward(kind='uniform')
# this should be zero
print(u1 - u1_sympy)
```

Best regards,

Thilo

**Comment by mikaem** [comment]
Ok, so I know what has happened. It's my fix for your other issue that's not deep enough. More exactly, it did not adjust for the optimized cython matvecs. I'll fix that in the master, it's not that hard:-)

**Comment by thoeschler** [comment]
Thanks for fixing this!

**Comment by thoeschler** [comment]
Hi Mikael,

I just noticed that the error didn't disappear for more complex functions. For example, if I set `u = x*(x - 100)*sin(x)*y` in the example above I still get nonzero values for `u0 - u0_sympy`.

**Comment by mikaem** [comment]
Perhaps you just need larger N? The `sin` function is not that easily resolved with polynomials:-)

**Comment by thoeschler** [comment]
I tried it with `N = 40` and it didn't resolve the problem :-(

**Comment by mikaem** [comment]
With `N=40` I get an error norm `np.linalg.norm(u0 - u0_sympy)` of $10^{-10}$.

**Comment by thoeschler** [comment]
I somehow forgot that displaying the `sin` for a large domain like `(0, 50)` of course requires a polynomial degree that is much higher than for the standard `(-1, 1)`. My bad :-)
